USE [master]
GO

/****** Object:  Database [BuildingManagerDB]    Script Date: 10/6/2024 17:50:33 ******/
CREATE DATABASE [BuildingManagerDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BuildingManagerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BuildingManagerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BuildingManagerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BuildingManagerDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BuildingManagerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BuildingManagerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BuildingManagerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BuildingManagerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BuildingManagerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BuildingManagerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BuildingManagerDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BuildingManagerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BuildingManagerDB] SET  MULTI_USER 
GO

ALTER DATABASE [BuildingManagerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BuildingManagerDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BuildingManagerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BuildingManagerDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BuildingManagerDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BuildingManagerDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BuildingManagerDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BuildingManagerDB] SET  READ_WRITE 
GO

